site_name: Linux Course For Beginners
site_description: 'A linux docs site'
site_author: 'Salman Malik'
docs_dir: docs/
repo_name: 'Linux-Basics-Complete-Course-With-Notes-Slides'
repo_url: 'https://github.com/imsalmanmalik/Linux-Basics-Complete-Course-With-Notes-Slides'
nav:
    - Home: index.md
theme:
  name: 'material'
