site_name: Embark on your Linux mastery journey, one command at a time!
site_description: 'A linux docs site'
site_author: 'bob Malik'
docs_dir: docs/
repo_name: 'Linux-Basics-Complete-Course-With-Notes-Slides'
repo_url: 'https://github.com/imbobmalik/Linux-Basics-Complete-Course-With-Notes-Slides'
nav:
    - Home: index.md
theme:
  name: 'material'
